#pragma config(Sensor, dgtl1,  sonarSensor,         sensorSONAR_cm)
#pragma config(Sensor, in4,    lightSensor,         sensorReflection)
#pragma config(Sensor, dgtl8,   touchSensor,			sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop, reversed)
#include "../verkefni3/tasks.c"
#define sonarDist 45
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Forward until Close Proximity -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to drive forward at half speed until the Ultrasonic Sensor       *|
|*  detects an obstruction within 20 inches of it.                                                    *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  The Ultrasonic Sensor returns a value of '-1' when it is out of range from the nearest      *|
|*        object.  The range is from 0 to 255 inches, so make sure that the robot is within this      *|
|*        range or it may never run.                                                                  *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 9,10 sonarSensor         VEX Sonar Sensor      Front mounted, facing forward     *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	StartTask(StopIfNeed);
	while(true)
	{
		if(SensorValue(lightSensor) < 300)
		{
			if(SensorValue(sonarSensor) > sonarDist  || SensorValue(sonarSensor) == -1)
			{
				motor[rightMotor] = 63;
				motor[leftMotor]  = 63;
			} else{
				while(SensorValue(sonarSensor) < sonarDist + 10)
				{
					motor[rightMotor] = -63;
					motor[leftMotor]  = 63;
				}
			}
		}	else {
			motor[rightMotor] = 0;
			motor[leftMotor]  = 0;
		}
	}

}
