#pragma config(Sensor, dgtl8,   touchSensor,			sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop, reversed)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#include "../verkefni3/tasks.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - Clawbot Single Joystick Control -                                 *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both joysticks to drive the robot.The joystick buttons are used to raise and    *|
|*  lower the arm.  																				  *|
|*  The joystick buttons are used to open and close the claw.										  *|
|*																									  *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)	Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                           *|
|*    2)	Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                            *|
|*	  3)	Button 5U and 5L are on the front left side of the joystick.							  *|
|*	  3)	Button 6U and 6L are on the front right side of the joystick.							  *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]        [Name]          [Type]                               [Description]            *|
|*    Motor - Port 2   rightMotor    VEX 393 Motor                         Right drive motor          *|
|*    Motor - Port 6   clawMotor     VEX 393 Motor w/ Motor Controler 29   Claw motor                 *|
|*    Motor - Port 7   armMotor      VEX 393 Motor w/ Motor Controler 29   Arm motor                  *|
|*    Motor - Port 10  leftMotor     VEX 393 Motor                         Left drive motor           *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void armMotorSpeed(int n){
		motor[armMotor] = n;
	}

void clawMotorSpeed(int n){
	motor[clawMotor] = n;
}

task main ()
{
	StartTask(StopIfNeed);
	StartTask(BAtteryDisplay);

	while(1 == 1)
	{
		motor[leftMotor]  = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];


		if(vexRT[Btn5U] == 1)
		{
			armMotorSpeed(32);
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMotorSpeed(-16);
		}
		else
		{
			armMotorSpeed(0);
		}

		if(vexRT[Btn6U] == 1)
		{
			clawMotorSpeed(42);
		}
		else if(vexRT[Btn6D] == 1)
		{
			clawMotorSpeed(-16);
		}
		else
		{
			clawMotorSpeed(0);
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
