#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for .5m  backwards .5m            *|
|*                                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*                                                                                                    *|
\*-----------------------------------------------------------------------------------------------4246-*/

int power = 127;
int reversePower = power * -1;
int driveTime = 1000;
int stopTime = 250;

void driveForward(int driveTime, int counter){
	motor[rightMotor] = power;
	motor[leftMotor]  = power;
	wait1Msec(driveTime * counter);
}

void driveBackwards(int driveTime, int counter){
	motor[rightMotor] = reversePower;
	motor[leftMotor]  = reversePower;
	wait1Msec(driveTime * counter);
}

void driveStop(int stopTime){
	motor[rightMotor] = 0;
	motor[leftMotor]  = 0;
	wait1Msec(stopTime);
}



//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(1000);
	for (int i = 1; i <= 5; i++){
		driveForward(driveTime, i);
		driveStop(stopTime);
		driveBackwards(driveTime, i);
		driveStop(stopTime);

	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
