#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Gyro Based Turns - Basic
-This program instructs your robot to turn for the specified number of degrees in "degrees10".
-For best sensor results, clear out the gyro and manually configure it at the begging of the code.
-The Gyro is configured by default to provide values from 0 to -3600 for clockwise rotation,
 and 0 to 3600 for counter-clockwise rotation

Robot Model(s): Swervebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor
Analog Port 8       in8                 VEX Gyro              Top-center mounted,
                                                              away from the Cortex
----------------------------------------------------------------------------------------------------*/
void giroTurn(int degrees,bool counterclock){
	SensorType[in8] = sensorNone;
  wait1Msec(1000);
  SensorType[in8] = sensorGyro;
  wait1Msec(2000);

  while(abs(SensorValue[in8]) < degrees * 10)
  {
		if (counterclock){
		motor[rightMotor] = 70;
		motor[leftMotor] = -70;
		}
		else{
		motor[rightMotor] = -70;
		motor[leftMotor] = 70;
		}
  }
  motor[rightMotor] = -5;
  motor[leftMotor] = 5;
  wait1Msec(250);
}


task main()
{

	turn_giro(90,true);

}
